services:
  postgres:
    image: postgres:16
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5999:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console web
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-data:/data

#  app:
#    build: .
#    container_name: product-catalog
#    depends_on:
#      - postgres
#      - minio
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/catalog
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      AWS_ACCESS_KEY_ID: minio
#      AWS_SECRET_ACCESS_KEY: minio123
#      AWS_REGION: us-east-1
#      AWS_ENDPOINT: http://minio:9000
#      AWS_BUCKET: catalog-bucket

volumes:
  pgdata:
  minio-data: